---
- name: Create cloudadmins group
  ansible.builtin.group:
    name: cloudadmins
    state: present

- name: Create user accounts
  ansible.builtin.user:
    name: "{{ item }}"
    group: cloudadmins
    groups: wheel
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: ".ssh/id_rsa"
  loop:
    - user1000
    - user2000

- name: Add authorized SSH keys
  ansible.builtin.authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  loop:
    - user1000
    - user2000
