---
# Tasks for patching role

# Update all packages
- name: Update all packages
  yum:
    name: "{{ packages_to_update }}"
    state: latest
  register: reboot_required

# Trigger a reboot if required
- name: Reboot if required
  command: echo "system requires a reboot"
  async: 0
  poll: 0
  changed_when: reboot_required.changed == true
  notify: reboot_now

