---
- name: Add string to file conditionally
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Add string to file
      blockinfile:
        path: /tmp/conditional
        block: "This is my CentOS VM"
      when:
        - ansible_distribution == 'CentOS'
        - ansible_distribution_major_version == '8'
        - ansible_kernel == '4.18.0-193.el8.x86_64'

